---
title: "Pre-Course Information"
output:
  html_document: 
    theme: united
    highlight: tango
    toc: yes
    toc_float: yes
    number_sections: true
---

```{r, echo=FALSE}
htmltools::img(src = knitr::image_uri("./Images/LATree.PNG"),
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px; width:200px;')
```



## General Information

This is an introductory level course for Introduction to R. This course will cover basic concepts and give you the confidence to work independently.

In this course we emphasise the application of skills, and building confidence and resilience in programming in R so that you can continue to learn back at your desk. 

It is essential that you have frequent opportunities to practice what you have learn from day 1, as this is how you will embed your learning. 

The 2-day course involves practical exercises throughout and coursework which should be completed ready for the second day. 

There is also a session on the second day to play with your own data.

***

## Pre-Course Checklist:

* Install the new RStudio bundle on your laptop `(see instructions below)`

* Ensure RStudio can install packages `(see instructions below)`

* Save the data from the ZIP file to your hard drive.

* Complete this pre-course questionnaire:[Smart Survey](https://www.smartsurvey.co.uk/s/7L80I/)  

* Bring your laptop, charger, and your WIFI connector (contact Learning Academy immediately if you do not have a laptop)

* Please bring with you a water bottle, and a mug for hot drinks (not provided – however you have access to a hot water boiler. Please bring your own supplies) 

* Arrive 10 – 15 minutes before the course starts to get set up and ready to learn

***

## Install R and R studio


Please follow your departmental instructions for installing R and RStudio. 

Please ensure you leave adequate time for installation as this may vary from department to department.



### Set up R Studio {-}

This is vital for installing the packages we’ll use during the course. Packages are bundles of code and functions that allow you to extend the capability of R.

Your department may have its own rules about how you can download packages. 

Please ensure you’re aware of any local restrictions. For example, within ONS all our packages must be downloaded via an artifactory – you may have to request packages in your department. Please ensure you leave plenty of time before the course to have this actioned.

Packages we use during this course are

* tidyverse

* readxl

* janitor




## Course Materials


### Example Data Sets {-} 

During the course we will be exploring many of the data sets built into R you can find these by typing datasets:: into the console in RStudio.

Create a folder on your hard drive if possible (this will avoid connection/Wi-Fi problems) called `Intro_to_R.` Then extract the ZIP file to this location.
 

### Course Files {-}

You may also wish to access the course for answers during the course. 

These can be found in the “Sessions” folder. 










